# Generated by Django 5.0.2 on 2024-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=RHv5r36fX7k'),
        ),
    ]
